# Generated by Django 3.0.7 on 2020-06-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('question', models.TextField(blank=True, max_length=5000, null=True)),
                ('hit', models.CharField(blank=True, max_length=10, null=True)),
                ('time_limit', models.CharField(blank=True, max_length=10, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
