# Generated by Django 2.2.6 on 2020-07-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_hit', models.CharField(blank=True, max_length=10, null=True)),
                ('io_number', models.IntegerField(blank=True, null=True)),
                ('input', models.TextField(blank=True, max_length=10000, null=True)),
                ('output', models.TextField(blank=True, max_length=10000, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=5000, null=True)),
                ('hit', models.CharField(blank=True, max_length=10, null=True)),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('topic', models.CharField(blank=True, max_length=20, null=True)),
                ('subtopic', models.CharField(blank=True, max_length=20, null=True)),
                ('subsubtopic', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=20, null=True)),
                ('subsubcategory', models.CharField(blank=True, max_length=20, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MCQSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_hit', models.CharField(blank=True, max_length=10, null=True)),
                ('solution', models.CharField(blank=True, max_length=120, null=True)),
                ('correctness', models.BooleanField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.TextField(blank=True, max_length=5000, null=True)),
                ('hit', models.CharField(blank=True, max_length=10, null=True)),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('topic', models.CharField(blank=True, max_length=20, null=True)),
                ('subtopic', models.CharField(blank=True, max_length=20, null=True)),
                ('subsubtopic', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=20, null=True)),
                ('subsubcategory', models.CharField(blank=True, max_length=20, null=True)),
                ('time_limit', models.CharField(blank=True, max_length=10, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=120, null=True)),
                ('question_hit', models.CharField(blank=True, max_length=10, null=True)),
                ('time_taken', models.CharField(blank=True, max_length=10, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('solution', models.TextField(blank=True, max_length=100000, null=True)),
                ('verdict', models.BooleanField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
