# Generated by Django 3.0.7 on 2020-06-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200611_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=120, null=True)),
                ('question_hit', models.CharField(blank=True, max_length=10, null=True)),
                ('time_taken', models.CharField(blank=True, max_length=10, null=True)),
                ('answer', models.TextField(blank=True, max_length=100000, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
