# Generated by Django 3.0.7 on 2020-06-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='answer',
            new_name='solution',
        ),
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
