# Generated by Django 3.0.7 on 2020-06-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200611_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_hit', models.CharField(blank=True, max_length=10, null=True)),
                ('input_number', models.IntegerField(blank=True, null=True)),
                ('intput', models.TextField(blank=True, max_length=10000, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_hit', models.CharField(blank=True, max_length=10, null=True)),
                ('output_number', models.IntegerField(blank=True, null=True)),
                ('output', models.TextField(blank=True, max_length=10000, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
