# Generated by Django 3.0.7 on 2020-06-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_input_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='intput',
            new_name='input',
        ),
    ]
